FROM tomcat:9-jre8
LABEL vendor=DHUniWien

# Update packages, install Graphviz
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -q -y git maven openjdk-8-jdk \
    && apt-get install -y graphviz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Make the data directories
RUN mkdir -p /var/lib/stemmarest/conf \
    && chmod -R g+w /var/lib/stemmarest \
    && chmod -R +2000 /var/lib/stemmarest

# VS: Compile and package the web archive
WORKDIR "/"
RUN git clone https://github.com/seretan/tradition_repo.git
RUN cd tradition_repo && git checkout IRSB && mvn -Dmaven.test.skip=true package
WORKDIR "/tradition_repo"

# Copy the software and config
RUN cp target/stemmarest.war /usr/local/tomcat/webapps/ \
    && cp build/server.xml /usr/local/tomcat/conf/ \
    && cp build/tomcat-users.xml /usr/local/tomcat/conf/

# Set the appropriate environment variable
ENV STEMMAREST_HOME /var/lib/stemmarest

# Run the server
EXPOSE 8080
CMD ["catalina.sh", "run"]
